### PR TITLE
Fix formatting of code blocks

### PR DESCRIPTION
**Pull request by ddellsperger**
Make sure you've checked off all these things before submitting:

- [x] This pull request isn't for a company's fork, it's intended for the upstream Slate shared by everybody.
- [x] This pull request is submitted to the `dev` branch.
- [x] If it makes frontend changes, this pull request has been tested in the latest version of Firefox, Chrome, IE, and Safari.

This is small, but it's been bugging me

Before the change
image

After the Change
image

### CODE REVIEW

**Review by rohithmadhavan — APPROVED** [review]
Text and code aligns but we're now adding (BEFORE) and (AFTER) explicitly into the code blocks 😐

**Comment by pmeister** [comment]
> Text and code aligns but we're now adding (BEFORE) and (AFTER) explicitly into the code blocks 😐

@rohithmadhavan We were already doing that. See the BEFORE screenshot. (Very meta!)

**Comment by pmeister** [comment]
> > Text and code aligns but we're now adding (BEFORE) and (AFTER) explicitly into the code blocks 😐
> 
> @rohithmadhavan We were already doing that. See the BEFORE screenshot. (Very meta!)

Eh, maybe not. I guess the BEFORE/AFTER was added by this PR so maybe the BEFORE screenshot was taken sometime in the middle of the changes.

**Review by pmeister — COMMENTED** [review]
LGTM

**Review by pmeister — APPROVED** [review]

**Comment by ddellsperger** [comment]
I've removed the before/after, going to merge this and deploy with 4.35 items.

**Pull request merged**
